work_dir: ./work_dir/us_snr

# feeder
feeder: feeder.Us_Feeder_snr
train_feeder_args:
  data_path: ./data/train.pkl
test_feeder_args:
  data_path: ./data/test.pkl

# model
model: net.Us_CNN
model_args:
  channels: 13
  num_classes: 3

#optim
optimizer: 'Adam'
weight_decay: 1e-5
base_lr: 1e-3
step: [10, 50]

# training
device: 0
batch_size: 64 
test_batch_size: 64
num_epoch: 80
nesterov: True



